#!/usr/bin/with-contenv bash

_term() {
  echo "Caught SIGTERM signal!"
  if [ ! -z "$USER" ] && [ ! -z "$PASS" ]; then
    /usr/bin/transmission-remote -n "$USER":"$PASS" --exit
  else
    /usr/bin/transmission-remote --exit
  fi
}

        trap _term SIGTERM

if [ ! -z "$LOG_FILE" ] && [ ! -z "$LOG_LEVEL" ]; then
  s6-setuidgid abc /usr/bin/transmission-daemon \
  -logfile="$LOG_FILE" -log-${LOG_LEVEL} \
  -g /config -c /watch -f &

  wait
else
	s6-setuidgid abc /usr/bin/transmission-daemon \
	-g /config -c /watch -f &

	wait
fi
